name: Godot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  game_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Godot and Export Templates
      run: |
        echo "Current directory: $(pwd)" # Debug: Print the current directory
        ls -al # Debug: List all files and directories

        # Downloading Godot executable and templates
        wget https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_linux_headless.64.zip
        wget https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz

        # Unzipping downloaded files
        unzip Godot_v3.5.3-stable_linux_headless.64.zip
        unzip Godot_v3.5.3-stable_export_templates.tpz

        # Moving the export templates to the expected directory
        mkdir -p ~/.local/share/godot/templates/3.5.3.stable/
        mv templates/* ~/.local/share/godot/templates/3.5.3.stable/

        # Making Godot executable
        chmod +x Godot_v3.5.3-stable_linux_headless.64

    - name: Export Godot Game (Linux)
      run: |
        ./Godot_v3.5.3-stable_linux_headless.64 --export "Linux/X11" bin/UnearthLinux/Unearth.x86_64
        ls -al bin/UnearthLinux/ # Debug: List files in the output directory

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: UnearthLinux
        path: ./bin/UnearthLinux/Unearth.x86_64

    - name: Export Godot Game (Windows)
      run: |
        ./Godot_v3.5.3-stable_linux_headless.64 --export "Windows Desktop" bin/Unearth/Unearth.exe
        ls -al bin/Unearth/ # Debug: List files in the output directory

    - name: Download Godot Icon Script
      run: |
        wget https://raw.githubusercontent.com/pkowal1982/godoticon/master/ReplaceIcon.gd

    - name: Replace Icon in Windows Export
      run: |
        ./Godot_v3.5.3-stable_linux_headless.64 -s ReplaceIcon.gd Art/UnearthIcon.ico bin/Unearth/Unearth.exe

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Unearth
        path: ./bin/Unearth/Unearth.exe
