name: Automatic builds

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract Version from Tag
      id: version_info
      run: |
        TAG_VERSION=$(echo ${{ github.ref }} | cut -d'/' -f3)
        echo "FULL_VERSION=${TAG_VERSION}" >> $GITHUB_OUTPUT

    - name: Setup Godot
      uses: fantom-technologies-inc/godot-ci@v2
      with:
        version: 3.5.3

    - name: Export Godot Game
      run: |
        mkdir -p ./bin/Export${{ matrix.platform }}/Unearth
        godot --export "${{ matrix.platform == 'linux' && 'Linux/X11' || 'Windows Desktop' }}" ./bin/Export${{ matrix.platform }}/Unearth/Unearth${{ matrix.platform == 'linux' && '.x86_64' || '.exe' }}

    - name: Replace Icon in Windows Export with rcedit
      if: matrix.platform == 'windows'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64
        wget https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -O rcedit.exe
        wine64 rcedit.exe ./bin/ExportWindows/Unearth/Unearth.exe --set-icon Art/UnearthIcon.ico

    - name: Zip Exported Game
      run: |
        cd ./bin/Export${{ matrix.platform }}/
        zip -r ../Unearth-${{ steps.version_info.outputs.FULL_VERSION }}-${{ matrix.platform }}.zip ./

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: |
          ./bin/Unearth-${{ steps.version_info.outputs.FULL_VERSION }}-*.zip
