name: Godot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Export Godot Game (Linux)
      run: |
        # Downloading Godot executable and templates
        wget https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_linux_headless.64.zip
        wget https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz

        # Unzipping downloaded files
        unzip Godot_v3.5.3-stable_linux_headless.64.zip
        unzip Godot_v3.5.3-stable_export_templates.tpz

        # Making Godot executable and exporting the game
        chmod +x Godot_v3.5.3-stable_linux_headless.64
        ./Godot_v3.5.3-stable_linux_headless.64 --export "Linux/X11" my_game_linux.x86_64

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my_game_linux
        path: ./my_game_linux.x86_64

  windows_build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Export Godot Game (Windows)
      run: |
        # Downloading Godot executable and templates using PowerShell
        Invoke-WebRequest -Uri https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_win64.exe.zip -OutFile godot_win.zip
        Invoke-WebRequest -Uri https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz -OutFile templates.tpz

        # Unzipping downloaded files
        Expand-Archive -Path godot_win.zip -DestinationPath ./
        Expand-Archive -Path templates.tpz -DestinationPath ./

        # Exporting the game
        ./Godot_v3.5.3-stable_win64.exe --export "Windows Desktop" my_game_windows.exe

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my_game_windows
        path: ./my_game_windows.exe
