name: Release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract Version & Determine Patch
      run: |
        MAJOR_MINOR=$(grep "var major_minor" Autoload/Version.gd | awk -F\" '{print $2}')
        PATCH=$(git rev-list --count HEAD)
        FULL_VERSION="$MAJOR_MINOR.$PATCH"
        echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV

    - name: Download Artifacts from Build Workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        path: ./artifacts

    - name: Create Git Tag
      run: |
        git tag $FULL_VERSION
        git push origin $FULL_VERSION

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FULL_VERSION }}
        release_name: Release ${{ env.FULL_VERSION }}
        body: 'Release description here'
        draft: false
        prerelease: false

    - name: Upload Release Artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "./artifacts/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

